# Metrics dataset that comprises of vectors which will be searched for in job postings.

pl = [
    ['python', False],
    ['c#', False],
    ['c', False],
    ['c++', False],
    ['ruby', False],
    ['java', False],
    [['javascript', 'js'], False],
    [['html', 'html5'], False],
    ['css', False],
    ['sql', False],
    ['r', False],
    ['assembly', False],
    ['swift', False],
    ['pascal', False],
    [['objective-c', 'objectivec'], False],
    ['php', False],
    [['go', 'golang'], False],
    ['perl', False],
    ['f#', False],
    ['scala', False],
    ['apex', False],
    ['kotlin', False],
    [['typescript', 'ts'], False]
]

f = [
    [['dotnet', '.net', 'asp.net', 'aspnet', 'net'], False],
    [['react', 'reactjs', 'react.js'], False],
    [['angular', 'angular.js', 'angularjs'], False],
    ['django', False],
    ['splunk', False],
    ['spring', False],
    ['rails', False],
    ['redux', False],
    [['express', 'expressjs', 'express.js'], False],
    [['vue', 'vuejs', 'vue.js'], False],
    ['flask', False],
    ['laravel', False],
    ['symfony', False],
    [['gatsby', 'gatsbyjs', 'gatsby.js'], False],
    ['sinatra', False],
    ['materialize', False],
    ['bootstrap', False],
    ['tailwind', False],
    ['ionic', False],
    ['xamarin', False],
    ['phonegap', False],
    ['native', False],
    ['corona', False],
    ['jquery', False],
    ['flutter', False],
    ['pytorch', False],
    ['pandas', False],
    [['sci-kit', 'scikit'], False],
    [['ml.net', 'mlnet'], False],
    ['chainer', False],
    ['pytest', False],
    ['jest', False],
    ['mocha', False],
    ['jasmine', False],
    ['cypress', False],
    ['scrapy', False],
    [['node', 'nodejs', 'npm'], False],
    [['git', 'github'], False],
    [['api', 'apis'], False],
    [['sdk', 'sdks'], False],
    [['postgres', 'postgresql', 'psql'], False],
    ['mysql', False],
    ['docker', False],
    ['jenkins', False],
    ['jira', False],
    [['rally','rallydev'], False],
    ['azure', False],
    ['kubernetes', False],
    ['swagger', False],
    [['scrum', 'agile', False]]
]