class CardMetrics:
    '''
    The dataset variables which will be analyzed in this project.
    '''
    programming_languages = [
        ['python', False],
        ['c#', False],
        ['c', False],
        ['c++', False],
        ['ruby', False],
        ['java', False],
        [['javascript', 'js'], False],
        [['html', 'html5'], False],
        ['css', False],
        ['sql', False],
        ['r', False],
        ['assembly', False],
        ['swift', False],
        ['pascal', False],
        [['objective-c', 'objectivec'], False],
        ['php', False],
        [['go', 'golang'], False],
        ['perl', False],
        ['f#', False],
        ['scala', False],
        ['apex', False],
        ['kotlin', False],
        ['typescript', False]
    ]

    frameworks = [
        [['dotnet', '.net', 'asp.net', 'aspnet', 'net'], False],
        ['react', False],
        ['angular', False],
        ['django', False],
        ['splunk', False],
        ['spring', False],
        ['rails', False],
        ['redux', False],
        ['express', False],
        ['vue', False],
        ['flask', False],
        ['laravel', False],
        ['symfony', False],
        ['gatsby', False],
        ['sinatra', False],
        ['materialize', False],
        ['bootstrap', False],
        ['tailwind', False],
        ['ionic', False],
        ['xamarin', False],
        ['phonegap', False],
        ['native', False],
        ['corona', False],
        ['jquery', False],
        ['flutter', False],
        ['pytorch', False],
        ['pandas', False],
        [['sci-kit', 'scikit'], False],
        [['ml.net', 'mlnet'], False],
        ['chainer', False],
        ['pytest', False],
        ['jest', False],
        ['mocha', False],
        ['jasmine', False],
        ['cypress', False],
        ['scrapy', False],
        [['node', 'nodejs', 'npm'], False],
        [['git', 'github'], False],
        [['api', 'apis'], False],
        [['sdk', 'sdks'], False],
        [['postgres', 'postgresql', 'psql'], False],
        ['mysql', False],
        ['docker', False],
        ['jenkins', False],
        ['jira', False],
        [['rally','rallydev'], False],
        ['azure', False],
        ['kubernetes', False]
    ]